config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :events
  resources :bookmarks

  devise_for :users
  resources :hotels

 root 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

	  @q = Hotel.ransack(params[:q])
	  @hotels = @q.result(distinct: true)

  	@all_hotels = Hotel.all
  	@all_events = Event.all

  	@bookmark = Bookmark.new
  	
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<div class="container">
	<div class="row">



<br><br>
        <div class="col-md-6">
          <div class="list-group-item list-group-item-success row">
            Hotels
          </div>
          <% Hotel.assign_headers.each do |f| %>
            <% hotel_details = Hotel.hotel_info(f["HotelInfo"]["HotelCode"]) %>
            <div class="list-group-item row">
            <div class="col-md-5">
                <%= image_tag(f["HotelImageInfo"]["ImageItem"]["Image"]["Url"]) %>

            </div>
              <div class="col-md-6">
                <h3><%= f["HotelInfo"]["HotelName"] %></h3>
                <h5><%= hotel_details["Address"].capitalize %></h5>
                <h5><%= hotel_details["City"].capitalize %></h5>
                <h6>40 people liked this hotel in the last 3 hours</h6>
                <h4 style="color:red;">Average Rate: $<%= f["HotelRateInfo"]["RatePlan"]["Rate"]["AverageNightlyRate"] %></h4>
              </div>

            <% if user_signed_in? %>
              <div style="float:right;">
              <% if Bookmark.find_by(user_id: current_user.id, hotel_id: f["HotelInfo"]["HotelCode"]) %>      
                <%= image_tag("bookmarked.png") %>
              <% else %>
                <%= simple_form_for @bookmark do |form| %>
                  <%= form.hidden_field :user_id, value: current_user.id %>
                  <%= form.hidden_field :hotel_id, value: f["HotelInfo"]["HotelCode"] %>
                  <%= form.submit "Bookmark", type: :image, src: image_path("not-bookmarked.png") %>
                <% end %>
              <% end %>
              </div>
            <% end %>
          </div>

          <% end %>
        </div>

       
        <div class="col-md-5 col-md-offset-1">
    	 	<div class="list-group">
    	 		<div class="list-group-item list-group-item-warning row">
    	 			Events
    	 		</div>
			<% @all_events.each do |h| %>
	    	 	<div class="list-group-item row">
            <div class="col-md-3">
              <%= image_tag("event1.png") %>
            </div>
            <div class="col-md-9">
              <%= link_to h.name, event_path(h.id) %>
              <div style="float:right;"><%= link_to image_tag("not-bookmarked.png"), '#' %></div>
            </div>

	    		</div>

	         <% end %>
    	 	</div>
        	 </div>
        </div>	

</div>	
<br><br>