config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :events
  resources :bookmarks

  devise_for :users
  resources :hotels

 root 'static_pages#home'

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base

	def get_hotel
		Hotel.all.each do |h|
			@hotels["name"] = h.name
			@hotels["address"] = h.address
		end
	end

	def self.assign_headers  # API Call starts here

	query = {  #Copied this from the Request Body on the Sabre Dev Studio site

    "GetHotelAvailRQ": {

        "SearchCriteria": {

            "GeoRef": {

                "RefPoint": {

                    "CountryCode": "SG",

                    "RefPointType": "6",

                    "ValueContext": "CODE",

                    "Value": "SIN"

                },

                "Radius": 40.0,

                "UOM": "MI",

                "Category": "HOTEL"

            },

            "RateInfoRef": {

                "CurrencyCode": "USD",

                "StayDateRange": {

                    "StartDate": "2016-10-21",

                    "EndDate": "2016-10-22"

                },

                "GuestCount": {

                    "Count": 2

                }

            },

            "HotelPref": {



            },

            "ImageRef": {

                "Type": "SMALL",

                "LanguageCode": "EN"

            }

        }

    }

}


		headers = {  # Copied this from the Request Headers from the Sabre Dev Studio Site
  			"Authorization" => "Bearer T1RLAQJ1e+XtyGArgjGsOIRgVlzaw6vVvhDCAGHKpkgC+Tv2ZCSix5DWAACgP8W0s9lG9D1c/0Nd/fAbVQ3hGi19R34p/0C4Y/YwEotqH2YQ+pHaCyJ32jhIrZXyfDvw/f0NfHf5mv0no1PhWfQWxg27I8e7ln1G5K4JX3X+OhOgwujLDVHQ3+C6U4cHwf0cMifY1ENk9fOye4IA6jR+49/zzVNiMtHIE7M06Hl173KPZGqFCfDkWtcoiyphHpMEnoffHg34vvPt0mXSiA**",
  			"X-Originating-Ip" => "122.11.135.54",
  			"Content-Type" => "application/json" 
		}

		@response = HTTParty.post( # this is a rails specific gem that consolidates everything and makes the call to Sabre API
  			"https://api.test.sabre.com/v1.0.0/shop/hotels?mode=avail", 
  			:body => query.to_json,
  			:headers => headers
		)

		@response["GetHotelAvailRS"]["HotelAvailInfos"]["HotelAvailInfo"] #this returns a formatted response, getting the specific information on the hotel availability

	end

	def self.hotel_info(hotelcode)


		query = {

		    "GetHotelContentRQ": {

		        "SearchCriteria": {

		            "HotelRefs": {

		                "HotelRef": [{

		                    "HotelCode": hotelcode

		                }, {

		                    "HotelCode": hotelcode

		                }]

		            },

		            "DescriptiveInfoRef": {

		                "PropertyInfo": true,

		                "LocationInfo": true,

		                "Amenities": true,

		                "Descriptions": {

		                    "Description": [{

		                        "Type": "Dining"

		                    }, {

		                        "Type": "Alerts"

		                    }]

		                },

		                "Airports": true,

		                "AcceptedCreditCards": true

		            },

		            "ImageRef": {

		                "MaxImages": "10"

		            }

		        }

		    }

		}


		headers = { 
  			"Authorization" => "Bearer T1RLAQJ1e+XtyGArgjGsOIRgVlzaw6vVvhDCAGHKpkgC+Tv2ZCSix5DWAACgP8W0s9lG9D1c/0Nd/fAbVQ3hGi19R34p/0C4Y/YwEotqH2YQ+pHaCyJ32jhIrZXyfDvw/f0NfHf5mv0no1PhWfQWxg27I8e7ln1G5K4JX3X+OhOgwujLDVHQ3+C6U4cHwf0cMifY1ENk9fOye4IA6jR+49/zzVNiMtHIE7M06Hl173KPZGqFCfDkWtcoiyphHpMEnoffHg34vvPt0mXSiA**",
  			"X-Originating-Ip" => "122.11.135.54",
  			"Content-Type" => "application/json" 
		}

		@httpresponse = HTTParty.post(
  			"https://api.test.sabre.com/v1.0.0/shop/hotels/content?mode=content", 
  			:body => query.to_json,
  			:headers => headers
		)

		dictionaryhotel = Hash.new
		if !@httpresponse["GetHotelContentRS"]["HotelContentInfos"]["HotelContentInfo"].nil?
			@httpresponse["GetHotelContentRS"]["HotelContentInfos"]["HotelContentInfo"].each do |h|
	          dictionaryhotel["Address"] = h["HotelDescriptiveInfo"]["LocationInfo"]["Address"]["AddressLine1"]
	          dictionaryhotel["City"] = h["HotelDescriptiveInfo"]["LocationInfo"]["Address"]["CityName"]
	        end
	     end

        return dictionaryhotel

	end
		


end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:name, :address, :rating, :rating_count)
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_for(@hotel) do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :rating_count %><br>
    <%= f.text_field :rating_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing Hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

<h1>Listing Hotels</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Address</th>
      <th>Rating</th>
      <th>Rating count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= image_tag("room1.jpg") %></td>
        <td><%= hotel.name %></td>
        <td><%= hotel.address %></td>
        <td><%= hotel.rating %></td>
        <td><%= hotel.rating_count %></td>
        <td><%= link_to 'Show', hotel %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
        <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel', new_hotel_path %>

</div>

app/views/hotels/new.html.erb
<div class="container">
	<div class="col-md-6 col-md-offset-3">
		<h1>New Hotel</h1>

		<%= render 'form' %>

		<%= link_to 'Back', hotels_path %>

	</div>	
</div>

app/views/hotels/show.html.erb
<div class="container">
	<div class="col-md-3">
		<p id="notice"><%= notice %></p>

		<p>
		  <strong>Name:</strong>
		  <%= @hotel.name %>
		</p>

		<p>
		  <strong>Address:</strong>
		  <%= @hotel.address %>
		</p>

		<p>
		  <strong>Rating:</strong>
		  <%= @hotel.rating %>
		</p>

		<p>
		  <strong>Rating count:</strong>
		  <%= @hotel.rating_count %>
		</p>

		<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
		<%= link_to 'Back', hotels_path %>

	</div>
	<div class="col-md-6">
		
	</div>
</div>